### ISSUE TITLE
generate_package_lists.sh can't handle archful SRPMs with an older dist-tag

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/baseruntime-package-lists#14]
While trying to process Rawhide, I received the following error:

```
[sgallagh@sgallaghp50:baseruntime-package-lists (master)]$ ./generate_module_lists.sh --version Rawhide  --arch x86_64
Processing runtime for x86_64
Traceback (most recent call last):
  File "/home/sgallagh/.local/bin/depchase", line 4, in <module>
    __import__('pkg_resources').run_script('depchase==1', 'depchase')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1507, in run_script
    exec(script_code, namespace, namespace)
  File "/home/sgallagh/.local/lib/python3.6/site-packages/depchase-1-py3.6.egg/EGG-INFO/scripts/depchase", line 456, in <module>
  File "/home/sgallagh/.local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sgallagh/.local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sgallagh/.local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sgallagh/.local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sgallagh/.local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sgallagh/.local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sgallagh/.local/lib/python3.6/site-packages/depchase-1-py3.6.egg/EGG-INFO/scripts/depchase", line 430, in resolve
  File "/home/sgallagh/.local/lib/python3.6/site-packages/depchase-1-py3.6.egg/EGG-INFO/scripts/depchase", line 329, in solve
  File "/home/sgallagh/.local/lib/python3.6/site-packages/depchase-1-py3.6.egg/EGG-INFO/scripts/depchase", line 329, in <genexpr>
  File "/home/sgallagh/.local/lib/python3.6/site-packages/depchase-1-py3.6.egg/EGG-INFO/scripts/depchase", line 308, in get_sourcepkg
AssertionError: Could not find source package for grub2-2.02-0.38.fc26.src
Depchase failures encountered on x86_64 runtime:
```

This is because the grub2 package currently in Rawhide still has a .fc26 dist-tag, but the archful-SRPM regeneration ends up with a .fc27 dist-tag. We need a way to "trick" libsolv into using the regenerated fc27 version here.

Tagging @ignatenkobrain for his thoughts.

**Comment by igor-raits** [comment]
no, we just need to regenerate packages properly.... =)
